@base = http://localhost:5000

### Accès raccourci
GET {{base}}/horizon
###
GET {{base}}/stackoverflow


### Création d'un raccourci

POST {{base}}/horizon
Content-Type: application/json

{
    "target": "https://store.steampowered.com/app/1151640/Horizon_Zero_Dawn_Complete_Edition/",
    "password": "aloy4ever"
}

### Création d'un raccourci

POST {{base}}/stackoverflow
Content-Type: application/json

{
    "target": "https://stackoverflow.com/",
    "password": "stackoverflow"
}

### Mise à jour du raccourci
PUT  {{base}}/horizon
Content-Type: application/json

{
    "target": "https://www.playstation.com/fr-fr/games/horizon-zero-dawn/",
    "password": "playstation"
}

### Suppression du raccourci

DELETE {{base}}/horizon?password=aloy4ever

### Suppression du raccourci
DELETE {{base}}/stackoverflow?password=stackoverflow
