@base = http://localhost:5000

### Ajout d'un raccourci

POST {{base}}/horizon
Content-Type: application/json

{
    "target": "https://store.steampowered.com/app/1151640/Horizon_Zero_Dawn_Complete_Edition/",
    "password": "aloy4ever"
}
### Accès au raccourci via le navigateur (ctrl+clic) http://localhost:5000/horizon

### Ajout d'un raccourci

POST {{base}}/stackoverflow
Content-Type: application/json

{
    "target": "https://stackoverflow.com/",
    "password": "stackoverflow"
}

### Accès au raccourci via le navigateur (ctrl+clic) http://localhost:5000/stackoverflow

### Suppression du raccourci

DELETE {{base}}/horizon?password=aloy4ever

###
DELETE {{base}}/stackoverflow?password=stackoverflow
